--- #YAML:1.0
name:               Text-Similarity
version:            0.09
abstract:           Measure the pair-wise Similarity of Files or Strings 
author:
    - Ted Pedersen <tpederse at d.umn.edu>
license:            gpl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
