=head1 NAME

CHANGES - Revision history for Text::Similarity

=head1 DESCRIPTION

=item 0.07

Released November 14, 2008 (all changes by TDP)

=over 

=item

Changed test case that was tripping up Windows. In Linux these are 
treated as being the same (when order doesn't matter) but this is not 
the case in Windows. 

	'sir winston churchill' 'winston churchill SIR!!!' 

The case has been changed to :

	'sir winston churchill' 'winston churchill sir' 

=back

=item 0.06

Released April 5, 2008 (all changes by TDP)

=over

=item

Added Dice coefficient to Overlaps.pm output. Dice is equivalent to 
F-measure, but formulated slightly differently so could be useful to 
catch errors. 

=item

Modified Overlaps method to provide lesk text matching score, that is 
the sum of the squared lengths of all phrasal matches 
(optionally normalized by the product of the lengths of the strings). It 
provides both Raw lesk and lesk (the normalized form) when run in 
verbose mode. 

=item

Reogranized some documentation to make it more clear that Overlaps is
just one possible way of measuring similarity, and that other methods can
and should be added.

=item

Renamed text_compare.pl as the more natural and fitting text_similarity.pl

=back

=item 0.05

Released April 4, 2008 (all changes by TDP)

=over

=item 

Made it possible for users to input strings directly via text_compare.pl and
getSimilarityStrings. Previously it was only possible to directly measure the 
similarity of files, but now strings can be measured. 

=back

=item 0.04

Released March 21, 2008 (all changes by TDP)

=over

=item 

Introduced tests for text_compare.pl (t/text_compare.t) - added support 
for os neutral file reads via FILE::SPEC in this and other .t files.

=item

Introduced tests for getOverlaps (t/overlaps.t)

=item

Improved synopsis examples to show how to pass options via arguments in 
hashes

=item

Clarified that stemming and compounding are not currently supported
disabled compfile option in text_compare.pl

=item

Made file handling in text_compare more robust so that when a file does 
not exist an error message is given and failure is immediate

=item

Changed method of passing constants in test cases from (eg.)
"Text::Similarity::NORMALIZE" to "normalize" in order to support 
backwards compatability with perl 5.6.

=item 

Introduce normalize and no-normalize tests for getSimilarity

=item

Fix Similarity.pm Synopsis example not to use files in /t that are no 
longer available

=back

=item 0.03 

Released March 20, 2008 (all changes by TDP)

=over

=item 

fix divide by zero errors reported on cpan by cernst at esoft.com, who also provided fix

=item

update test cases to improve coverage of partial matches and no matches

=item

update synopsis examples so they can be run via cut and paste

=item

improve README content to make it more descriptive

=item

introduce /doc directory for pod of INSTALL README and CHANGES

=item

introduce 'use constant' to support perl 5.6

=back

=item 0.02 

Released October 16, 2004, all changes by JM

=over

=item 

fixed overlap finding & added new module Text::OverlapFinder

=item 

improved command-line interface

=item 

improved documentation and help messages

=item 

added support for a stoplist

=back

=item 0.01 

Released September 23, 2004, all changes by JM

=over

=item 

original version; created by h2xs 1.23 with options -b 5.6.0 -A -X Text::Similarity

=back

=head1 AUTHORS

 Ted Pedersen, University of Minnesota, Duluth
 tpederse at d.umn.edu

This document last modified by :
$Id: CHANGES.pod,v 1.14 2008/11/15 02:07:18 tpederse Exp $

=head1 SEE ALSO

=head1 COPYRIGHT AND LICENSE

Copyright (c) 2004-2008 Ted Pedersen

Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU Free Documentation License, Version 1.2
or any later version published by the Free Software Foundation;
with no Invariant Sections, no Front-Cover Texts, and no Back-Cover
Texts.

Note: a copy of the GNU Free Documentation License is available on
the web at L<http://www.gnu.org/copyleft/fdl.html> and is included in
this distribution as FDL.txt.

=cut

